### ISSUE TITLE
ClassNotFoundException FilterRegistrationBean

### ISSUE THREAD

**Issue by phuongtailtranminh** [hdiv/spring-boot-sample-hdiv#2]
I'm trying to integrate HDIV with Spring Boot 1.5.1 (I tried version 1.5.3 also)

This is the configurations:

```
@Configuration
@EnableAutoConfiguration
@ComponentScan
public class WebConfig extends WebMvcConfigurerAdapter {
     ...
    @Bean
    public HdivConfig applicationWebSecurity() {
        return new HdivConfig();
    }

}
```

Hdiv config:

```
public class HdivConfig extends HdivWebSecurityConfigurerAdapter {

    @Override
    public void addExclusions(ExclusionRegistry registry) {
        registry.addUrlExclusions("/login");
    }

}
```

But when I start the application, I got this exception:

```
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```

**Comment by gillarramendi** [comment]
Current Hdiv for Spring Boot version only works with Spring Boot 1.3.x.
Spring Boot 1.5 is not supported.
Sorry for the inconvenience

**Comment by phuongtailtranminh** [comment]
Thanks you
